name: Custom Action Workflow

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/actionforge/test-action-registry:latest

  run-script-and-action:
    permissions:
      contents: read
      packages: read

    strategy:
      matrix:
        os: [ubuntu-latest,
          # Container action is only supported on Linux
          # macos-latest, windows-latest          
        ]

    runs-on: ${{ matrix.os }}
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run local bin-local.sh
        shell: bash
        run: bash ./bin-local.sh

      - name: Run container
        uses: ./
        with:
          input1: lorem
          input2: ipsum
          environment: true
